import { Question } from './types';

export const QUESTIONS: Question[] = [
  { id: 1, prefix: "I managed to find a great", suffix: "at the market yesterday.", answer: "bargain" },
  { id: 2, prefix: "The", suffix: "smiled politely as she packed my bags.", answer: "cashier" },
  { id: 3, prefix: "Please leave your items here before entering the", suffix: ".", answer: "changing room" },
  { id: 4, prefix: "You should change some money into the local", suffix: "before you travel.", answer: "currency" },
  { id: 5, prefix: "Can I", suffix: "this shirt for a larger size?", answer: "exchange" },
  { id: 6, prefix: "Always read the washing", suffix: "inside your clothes.", answer: "label" },
  { id: 7, prefix: "Keep your", suffix: "in case you need to return the item.", answer: "receipt" },
  { id: 8, prefix: "The store refused to give me a", suffix: "without proof of purchase.", answer: "refund" },
  { id: 9, prefix: "He bought a", suffix: "car to save some money.", answer: "second-hand" },
  { id: 10, prefix: "The supermarket offers a wide", suffix: "of fresh fruits.", answer: "variety" },
  { id: 11, prefix: "You need a code to", suffix: "the secure files.", answer: "access" },
  { id: 12, prefix: "I downloaded a new", suffix: "to help me learn Spanish.", answer: "application" },
  { id: 13, prefix: "My phone died because the", suffix: "was empty.", answer: "battery" },
  { id: 14, prefix: "She writes a popular travel", suffix: "about her adventures.", answer: "blog" },
  { id: 15, prefix: "The internet", suffix: "is very slow in this area.", answer: "connection" },
  { id: 16, prefix: "Be careful not to", suffix: "important documents by mistake.", answer: "delete" },
  { id: 17, prefix: "I prefer reading", suffix: "books on my tablet.", answer: "digital" },
  { id: 18, prefix: "It took ten minutes to", suffix: "the movie.", answer: "download" },
  { id: 19, prefix: "You must not share your", suffix: "with anyone.", answer: "password" },
  { id: 20, prefix: "We need to update the computer", suffix: "regularly.", answer: "software" },
  { id: 21, prefix: "The", suffix: "designed a very modern and unique house.", answer: "architect" },
  { id: 22, prefix: "We sat on the", suffix: "watching the sunset.", answer: "balcony" },
  { id: 23, prefix: "The room has a very high", suffix: "painted white.", answer: "ceiling" },
  { id: 24, prefix: "Please put the clean plates back in the", suffix: ".", answer: "cupboard" },
  { id: 25, prefix: "Wait for me at the main", suffix: "of the building.", answer: "entrance" },
  { id: 26, prefix: "Dad is fixing his car in the", suffix: ".", answer: "garage" },
  { id: 27, prefix: "The central", suffix: "keeps the house warm in winter.", answer: "heating" },
  { id: 28, prefix: "Our new", suffix: "is very friendly and helpful.", answer: "neighbour" },
  { id: 29, prefix: "The monthly", suffix: "for this apartment is quite high.", answer: "rent" },
  { id: 30, prefix: "My bedroom is located", suffix: "on the second floor.", answer: "upstairs" },
  { id: 31, prefix: "I decided to", suffix: "cake for her birthday.", answer: "bake" },
  { id: 32, prefix: "This coffee tastes too", suffix: "without sugar.", answer: "bitter" },
  { id: 33, prefix: "You should", suffix: "the potatoes for twenty minutes.", answer: "boil" },
  { id: 34, prefix: "We usually eat lunch in the school", suffix: ".", answer: "canteen" },
  { id: 35, prefix: "That chocolate cake looks absolutely", suffix: ".", answer: "delicious" },
  { id: 36, prefix: "He is on a strict", suffix: "to lose weight.", answer: "diet" },
  { id: 37, prefix: "We plan to", suffix: "some sausages in the garden.", answer: "grill" },
  { id: 38, prefix: "Light", suffix: "will be served during the break.", answer: "refreshments" },
  { id: 39, prefix: "I cannot eat very", suffix: "food because it burns my mouth.", answer: "spicy" },
  { id: 40, prefix: "She ordered a", suffix: "meal with no meat.", answer: "vegetarian" },
  { id: 41, prefix: "He was", suffix: "because the bus was late again.", answer: "annoyed" },
  { id: 42, prefix: "I feel very", suffix: "before speaking in public.", answer: "anxious" },
  { id: 43, prefix: "It was very", suffix: "of him to rescue the cat.", answer: "brave" },
  { id: 44, prefix: "Don't be so", suffix: "with your belongings.", answer: "careless" },
  { id: 45, prefix: "She is always", suffix: "and makes everyone smile.", answer: "cheerful" },
  { id: 46, prefix: "I was", suffix: "that the concert was cancelled.", answer: "disappointed" },
  { id: 47, prefix: "He felt", suffix: "when he forgot her name.", answer: "embarrassed" },
  { id: 48, prefix: "Thank you for your", suffix: "donation to the charity.", answer: "generous" },
  { id: 49, prefix: "I am very", suffix: "on learning how to play the guitar.", answer: "keen" },
  { id: 50, prefix: "It was a", suffix: "decision to wear a raincoat today.", answer: "sensible" }
];